const data = [
  {
    id: "1",
    categoria: "Aceites",
    nombre: "Aceite 900 cc",
    descripcion: "loren ipsum dolor sit amet consectetur adipisicing elit",
    precio: 400,
    imagen: "../../img/aceiteCocinero.png",
    stock: 500,
  },
  {
    id: "2",
    categoria: "Harinas",
    nombre: "Harina 000 1 kg",
    descripcion: "loren ipsum dolor sit amet consectetur adipisicing elit ",
    precio: 150,
    imagen: "../../img/harinaFavorita.jpg",
    stock: 250,
  },
  {
    id: "3",
    categoria: "Yerbas",
    nombre: "Yerba c/Palo 1 kg",
    descripcion: "loren ipsum",
    precio: 440,
    imagen: "../../img/yerbaNG.jpg",
    stock: 650,
  },
  {
    id: "4",
    categoria: "Premezclas",
    nombre: "Bizcochuelo 450g",
    descripcion: "loren ipsum",
    precio: 272,
    imagen: "../../img/bizcochueloExq.jpg",
    stock: 410,
  },
  {
    id: "5",
    categoria: "Fideos",
    nombre: "Fideo Codito 500g",
    descripcion: "loren ipsum",
    precio: 125,
    imagen: "../../img/fideoMatarazzo.jpg",
    stock: 410,
  },
  {
    id: "6",
    categoria: "Arroz",
    nombre: "Arroz L.Fino 1kg",
    descripcion: "loren ipsum",
    precio: 245,
    imagen: "../../img/arrozGallo.jfif",
    stock: 350,
  },
];

export default data;
